name: CI
on:
  workflow_dispatch:

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    env:   # <--- 添加这里，强制使用 Node.js 24
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Build
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/hjiyu1965/android_kernel_zte_ums9620_mifi_f50
          kernel-branch: main
          config: sprd_debian_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 12
          aosp-clang-version: r416183b
          disable-lto: true
          anykernel3: true
